Repository pjhcsols/VirtualFitting_System, pull requests merged in 2025-04, with the labels that each got.

#106 [FE ← 🚀 FE_SONU] Admin Product Upload Page 제작
  virtualFittingApp/bun.lock
  virtualFittingApp/package.json
  virtualFittingApp/public/svg/UploadAsset.svg
  virtualFittingApp/public/svg/plus.svg
  virtualFittingApp/src/pages/admin/ui/AdminCreateProductPage.tsx
  virtualFittingApp/src/pages/admin/ui/css/AdminCreateProductPage.css.ts
  virtualFittingApp/src/shared/components/index.ts
  virtualFittingApp/src/shared/components/input/index.ts
  virtualFittingApp/src/shared/components/input/ui/InputAnimate.css.ts
  virtualFittingApp/src/shared/components/input/ui/InputAnimate.tsx
  virtualFittingApp/src/shared/components/precaution/index.ts
  virtualFittingApp/src/shared/components/precaution/ui/PreCaution.tsx
  virtualFittingApp/src/shared/constants/index.ts
  virtualFittingApp/src/shared/layout/admin/AdminLayout.tsx
  virtualFittingApp/src/widgets/admin/api/admin.action.ts
  virtualFittingApp/src/widgets/admin/constants/index.ts
  virtualFittingApp/src/widgets/admin/index.ts
  virtualFittingApp/src/widgets/admin/types/Product.d.ts
  virtualFittingApp/src/widgets/admin/ui/ProductEditor.tsx
  virtualFittingApp/src/widgets/admin/ui/ProductInputTag.tsx
  virtualFittingApp/src/widgets/admin/ui/ProductPreview.tsx
  virtualFittingApp/src/widgets/admin/ui/css/ProductEditor.css.ts
  virtualFittingApp/src/widgets/admin/ui/css/ProductInputTag.css.ts
  virtualFittingApp/src/widgets/admin/ui/css/ProductPreview.css.ts
Labels: feature, UI

#103 [FE ⬅🚀 FE_seah] Add Product Card to Store Page
  virtualFittingApp/public/font/Helvetica-light.ttf
  virtualFittingApp/public/font/Helvetica.ttf
  virtualFittingApp/public/font/HelveticaNeueBlack.otf
  virtualFittingApp/public/font/HelveticaNeueLight.otf
  virtualFittingApp/public/font/HelveticaNeueMedium.otf
  virtualFittingApp/public/font/HelveticaNeueThin.otf
  virtualFittingApp/public/font/Inter-VariableFont_opsz,wght.ttf
  virtualFittingApp/public/img/product/product_sample_1.png
  virtualFittingApp/public/img/product/product_sample_2.png
  virtualFittingApp/public/img/product/product_sample_3.png
  virtualFittingApp/src/pages/store/constants/dummy.ts
  virtualFittingApp/src/pages/store/ui/StorePage.tsx
  virtualFittingApp/src/shared/components/header/ui/Header.tsx
  virtualFittingApp/src/shared/components/header/ui/NewHeader.tsx
  virtualFittingApp/src/shared/components/index.ts
  virtualFittingApp/src/shared/components/product-card/index.tsx
  virtualFittingApp/src/shared/components/product-card/ui/ProductCard.tsx
  virtualFittingApp/src/shared/layout/store/StoreLayout.tsx
  virtualFittingApp/src/widgets/store/ui/Carousel.tsx
Labels: feature, UI

#110 [FE 👈 🚀FE_SONU] Brand Mypage 작업 완료 & Brand Product Register 페이지 예외처리 완료
  virtualFittingApp/public/img/logo/BasiliumLogo.svg
  virtualFittingApp/public/svg/SearchIcon.svg
  virtualFittingApp/src/app/admin/AdminRouter.tsx
  virtualFittingApp/src/app/brand/BrandRouter.tsx
  virtualFittingApp/src/app/my/MyRouter.tsx
  virtualFittingApp/src/entity/index.ts
  virtualFittingApp/src/entity/product/Product.d.ts
  virtualFittingApp/src/pages/admin/index.ts
  virtualFittingApp/src/pages/admin/ui/AdminProductListPage.tsx
  virtualFittingApp/src/pages/admin/ui/AdminProductPage.tsx
  virtualFittingApp/src/pages/admin/ui/css/AdminProductListPage.css.ts
  virtualFittingApp/src/pages/admin/ui/css/AdminProductPage.css.ts
  virtualFittingApp/src/pages/brand/api/brand.action.ts
  virtualFittingApp/src/pages/brand/constants/index.ts
  virtualFittingApp/src/pages/brand/index.ts
  virtualFittingApp/src/pages/brand/types/brandUser.d.ts
  virtualFittingApp/src/pages/brand/ui/BrandDashboard.tsx
  virtualFittingApp/src/pages/brand/ui/BrandPage.tsx
  virtualFittingApp/src/pages/brand/ui/BrandProductCreate.tsx
  virtualFittingApp/src/pages/brand/ui/BrandProfile.tsx
  virtualFittingApp/src/pages/brand/ui/css/BrandDashboard.css.ts
  virtualFittingApp/src/pages/brand/ui/css/BrandPage.css.ts
  virtualFittingApp/src/pages/brand/ui/css/BrandProductCreate.css.ts
  virtualFittingApp/src/pages/brand/ui/css/BrandProfile.css.ts
  virtualFittingApp/src/pages/main/ui/MainPage.tsx
  virtualFittingApp/src/pages/store/ui/StorePage.tsx
  virtualFittingApp/src/shared/components/card/index.ts
  virtualFittingApp/src/shared/components/card/ui/BasiliumCard.tsx
  virtualFittingApp/src/shared/components/card/ui/ProductCard.tsx
  virtualFittingApp/src/shared/components/card/ui/css/BasiliumCard.css.ts
  virtualFittingApp/src/shared/components/header/index.ts
  virtualFittingApp/src/shared/components/header/ui/AdminHeader.tsx
  virtualFittingApp/src/shared/components/header/ui/BrandHeader.tsx
  virtualFittingApp/src/shared/components/header/ui/css/BrandHeader.css.ts
  virtualFittingApp/src/shared/components/input/ui/Profile.tsx
  virtualFittingApp/src/shared/components/progress/index.ts
  virtualFittingApp/src/shared/components/progress/ui/ProgressBar.tsx
  virtualFittingApp/src/shared/components/searchBar/index.ts
  virtualFittingApp/src/shared/components/searchBar/ui/BrandSearch.tsx
  virtualFittingApp/src/shared/constants/index.ts
  virtualFittingApp/src/shared/layout/brand/BrandLayout.tsx
  virtualFittingApp/src/shared/layout/index.ts
  virtualFittingApp/src/shared/types/product/category.d.ts
  virtualFittingApp/src/widgets/admin/constants/index.ts
  virtualFittingApp/src/widgets/admin/types/Product.d.ts
  virtualFittingApp/src/widgets/admin/ui/ProductEditor.tsx
  virtualFittingApp/src/widgets/admin/ui/ProductInputTag.tsx
  virtualFittingApp/src/widgets/admin/ui/ProductPreview.tsx
  virtualFittingApp/src/widgets/admin/ui/css/ProductInputTag.css.ts
  virtualFittingApp/src/widgets/admin/ui/css/ProductPreview.css.ts
  virtualFittingApp/src/widgets/brand/index.ts
  virtualFittingApp/src/widgets/brand/ui/BrandButton.tsx
  virtualFittingApp/src/widgets/brand/ui/BrandInfoChanger.tsx
  virtualFittingApp/src/widgets/brand/ui/css/BrandButton.css.ts
  virtualFittingApp/src/widgets/brand/ui/css/BrandInfoChanger.css.ts
  virtualFittingApp/src/widgets/index.ts
Labels: feature, UI

#111 [FE ⬅🚀 FE_seah] Refactor StoreDetail Page and Add Routing
  virtualFittingApp/public/svg/like.svg
  virtualFittingApp/public/svg/share.svg
  virtualFittingApp/src/app/store/StoreRouter.tsx
  virtualFittingApp/src/pages/store/ui/StoreDetailPage.tsx
  virtualFittingApp/src/pages/store/ui/StorePage.tsx
  virtualFittingApp/src/shared/components/product-card/ui/ProductCard.tsx
  virtualFittingApp/src/shared/components/product/ui/ProductSmallCard.tsx
  virtualFittingApp/src/shared/constants/index.ts
  virtualFittingApp/src/widgets/store/ui/ProductContainer.tsx
Labels: Refactor

#114 [FE ← 🚀 FE_SONU] Product Register Page & Product Judge Component & Product Input Widget Refactor
  virtualFittingApp/bun.lock
  virtualFittingApp/package.json
  virtualFittingApp/public/rive/CheckMark.riv
  virtualFittingApp/public/rive/XMark.riv
  virtualFittingApp/public/svg/loading.svg
  virtualFittingApp/src/app/admin/AdminRouter.tsx
  virtualFittingApp/src/pages/admin/index.ts
  virtualFittingApp/src/pages/admin/ui/AdminBrandControllPanel.tsx
  virtualFittingApp/src/pages/admin/ui/AdminLogin.tsx
  virtualFittingApp/src/pages/admin/ui/AdminProductListPage.tsx
  virtualFittingApp/src/pages/admin/ui/AdminProductPage.tsx
  virtualFittingApp/src/pages/admin/ui/css/AdminBrandControllPanel.css.ts
  virtualFittingApp/src/pages/admin/ui/css/AdminLogin.css.ts
  virtualFittingApp/src/pages/admin/ui/css/AdminProductListPage.css.ts
  virtualFittingApp/src/pages/admin/ui/css/AdminProductPage.css.ts
  virtualFittingApp/src/pages/brand/ui/BrandLogin.tsx
  virtualFittingApp/src/shared/components/checkMark/index.ts
  virtualFittingApp/src/shared/components/checkMark/ui/CheckMarkAnimation.tsx
  virtualFittingApp/src/shared/components/checkMark/ui/XMark.tsx
  virtualFittingApp/src/shared/components/index.ts
  virtualFittingApp/src/shared/components/input/index.ts
  virtualFittingApp/src/shared/components/input/ui/CategorySelector.tsx
  virtualFittingApp/src/shared/components/input/ui/FileUploader.tsx
  virtualFittingApp/src/shared/components/input/ui/InputAnimate.tsx
  virtualFittingApp/src/shared/components/input/ui/InputSizeTable.tsx
  virtualFittingApp/src/shared/components/input/ui/ProductInfo.tsx
  virtualFittingApp/src/shared/components/input/ui/ProductOptionUploader.tsx
  virtualFittingApp/src/shared/components/input/ui/css/CategorySelector.css.ts
  virtualFittingApp/src/shared/components/input/ui/css/FileUploader.css.ts
  virtualFittingApp/src/shared/components/input/ui/css/InputAnimate.css.ts
  virtualFittingApp/src/shared/components/input/ui/css/InputSizeTable.css.ts
  virtualFittingApp/src/shared/components/input/ui/css/ProductInfo.css.ts
  virtualFittingApp/src/shared/components/input/ui/css/ProductOptionUploader.css.ts
  virtualFittingApp/src/shared/components/product/ui/ProductOptionBar.tsx
  virtualFittingApp/src/shared/components/product/ui/css/ProductOptionBar.css.ts
  virtualFittingApp/src/shared/components/progress/ui/ProgressBar.tsx
  virtualFittingApp/src/shared/constants/index.ts
  virtualFittingApp/src/shared/layout/admin/AdminLayout.tsx
  virtualFittingApp/src/shared/types/index.ts
  virtualFittingApp/src/shared/types/product/option.d.ts
  virtualFittingApp/src/shared/types/product/product.d.ts
  virtualFittingApp/src/shared/utils/file/file.util.ts
  virtualFittingApp/src/shared/utils/index.ts
  virtualFittingApp/src/shared/utils/product/productValid.utils.ts
  virtualFittingApp/src/widgets/admin/constants/index.ts
  virtualFittingApp/src/widgets/admin/ui/JudgeStandard.tsx
  virtualFittingApp/src/widgets/admin/ui/ProductEditor.tsx
  virtualFittingApp/src/widgets/admin/ui/ProductInputTag.tsx
  virtualFittingApp/src/widgets/admin/ui/ProductPreview.tsx
  virtualFittingApp/src/widgets/admin/ui/css/JudgeStandard.css.ts
  virtualFittingApp/src/widgets/admin/ui/css/ProductInputTag.css.ts
  virtualFittingApp/src/widgets/admin/ui/css/ProductPreview.css.ts
  virtualFittingApp/src/widgets/brand/ui/BrandProductPreview.tsx
  virtualFittingApp/src/widgets/brand/ui/css/BrandProductPreview.css.ts
Labels: enhancement, feature, UI

#115 [FE ⬅🚀 FE_mj] Feat & Refacor: MyOrderPage & MyLikePage
  virtualFittingApp/public/svg/back.svg
  virtualFittingApp/public/svg/camera.svg
  virtualFittingApp/public/svg/female.svg
  virtualFittingApp/public/svg/male.svg
  virtualFittingApp/public/svg/myUser.svg
  virtualFittingApp/src/app/my/MyRouter.tsx
  virtualFittingApp/src/pages/my/api/order.action.ts
  virtualFittingApp/src/pages/my/api/submit.action.ts
  virtualFittingApp/src/pages/my/constants/index.ts
  virtualFittingApp/src/pages/my/index.ts
  virtualFittingApp/src/pages/my/types/order.d.ts
  virtualFittingApp/src/pages/my/ui/LikeContentList.tsx
  virtualFittingApp/src/pages/my/ui/MyCancel.tsx
  virtualFittingApp/src/pages/my/ui/MyLike.tsx
  virtualFittingApp/src/pages/my/ui/MyOrderList.tsx
  virtualFittingApp/src/pages/my/ui/MyOrderListDetail.tsx
  virtualFittingApp/src/pages/my/ui/MyPage.tsx
  virtualFittingApp/src/pages/my/ui/MyPageDetail.tsx
  virtualFittingApp/src/pages/my/ui/OrderContentList.tsx
  virtualFittingApp/src/pages/my/ui/alert.png
  virtualFittingApp/src/pages/my/ui/camera.png
  virtualFittingApp/src/pages/my/ui/female.png
  virtualFittingApp/src/pages/my/ui/male.png
  virtualFittingApp/src/shared/components/header/constants/index.ts
  virtualFittingApp/src/shared/components/header/ui/MyHeader.tsx
  virtualFittingApp/src/shared/components/header/ui/UserImg.png
  virtualFittingApp/src/shared/components/header/ui/back.png
  virtualFittingApp/src/shared/components/liked-carousel/api/liked.action.ts
Labels: feature, Refactor

#117 [FE ← 🚀 FE_SONU] BrandUser Dashboard page & BrandUser Product List Page & Pagination
  virtualFittingApp/src/app/brand/BrandRouter.tsx
  virtualFittingApp/src/index.css
  virtualFittingApp/src/pages/brand/api/brand.action.ts
  virtualFittingApp/src/pages/brand/index.ts
  virtualFittingApp/src/pages/brand/ui/BrandDashboard.tsx
  virtualFittingApp/src/pages/brand/ui/BrandProductList.tsx
  virtualFittingApp/src/pages/brand/ui/css/BrandDashboard.css.ts
  virtualFittingApp/src/pages/brand/ui/css/BrandProductList.css.ts
  virtualFittingApp/src/shared/components/card/index.ts
  virtualFittingApp/src/shared/components/card/types/DashboardObject.d.ts
  virtualFittingApp/src/shared/components/card/ui/BrandProductCard.tsx
  virtualFittingApp/src/shared/components/card/ui/DashboardObject.tsx
  virtualFittingApp/src/shared/components/card/ui/ProductCard.tsx
  virtualFittingApp/src/shared/components/card/ui/css/DashboardObject.css.ts
  virtualFittingApp/src/shared/components/card/ui/css/ProductCard.css.ts
  virtualFittingApp/src/shared/components/pagination/index.ts
  virtualFittingApp/src/shared/components/pagination/types/Pagination.d.ts
  virtualFittingApp/src/shared/components/pagination/types/pagination.d.ts
  virtualFittingApp/src/shared/components/pagination/ui/Pagination.tsx
  virtualFittingApp/src/shared/components/pagination/utils/pagination.utils.ts
  virtualFittingApp/src/shared/components/searchBar/ui/BrandSearch.tsx
  virtualFittingApp/src/widgets/admin/index.ts
Labels: feature, UI

#118 [FE ⬅🚀 FE_seah] Refactor StoreDetail Page
  virtualFittingApp/src/pages/store/ui/StoreDetailPage.tsx
  virtualFittingApp/src/shared/components/product/ui/ProductSmallCard.tsx
  virtualFittingApp/src/shared/layout/store/StoreLayout.tsx
  virtualFittingApp/src/widgets/store/ui/ProductContainer.tsx
Labels: UI, Refactor
