Repository pjhcsols/VirtualFitting_System, pull requests merged in 2025-08, with the labels that each got.

#159 [FE ⬅🚀 FE_seah] 결제 위젯 & 결제 API 연동
  virtualFittingApp/bun.lock
  virtualFittingApp/package.json
  virtualFittingApp/src/app/payment/PaymentRouter.tsx
  virtualFittingApp/src/features/index.ts
  virtualFittingApp/src/features/payment/api/payment.action.ts
  virtualFittingApp/src/features/payment/index.ts
  virtualFittingApp/src/features/payment/ui/CheckoutWidget.tsx
  virtualFittingApp/src/features/payment/ui/PaymentFaulurePopup.tsx
  virtualFittingApp/src/features/payment/ui/SuccessPage.tsx
  virtualFittingApp/src/shared/types/payment/payment.d.ts
  virtualFittingApp/src/widgets/store/ui/ProductContainer.tsx
Labels: Status:Mergeable

#163 [FE ← FE_SONU] File DragAndDrop 설정 & 회원가입 logic 설정
  virtualFittingApp/bun.lock
  virtualFittingApp/package.json
  virtualFittingApp/src/app/auth/AuthRouter.tsx
  virtualFittingApp/src/pages/auth/ui/BrandSignUpPage.tsx
  virtualFittingApp/src/pages/auth/ui/BrandUserSignUpProgressPage.tsx
  virtualFittingApp/src/shared/components/draggable/ui/DragAndDropFile.tsx
  virtualFittingApp/src/shared/layout/index.ts
  virtualFittingApp/src/shared/types/auth/authContext.d.ts
  virtualFittingApp/src/shared/types/file/File.d.ts
  virtualFittingApp/src/shared/types/index.ts
  virtualFittingApp/src/widgets/auth/api/brandAuth.action.ts
  virtualFittingApp/src/widgets/auth/hooks/useBrandSignup.tsx
  virtualFittingApp/src/widgets/auth/types/login.d.ts
  virtualFittingApp/src/widgets/auth/ui/BrandUserCompanySignUpPanel.tsx
Labels: feature

#167 [FE ⬅🚀FE_SONU] 회원가입 로직 성공 및 인증서 제출 로직 진행 + 역할군 별 로그인 라우팅 분리
  virtualFittingApp/bun.lock
  virtualFittingApp/package.json
  virtualFittingApp/src/app/brand/BrandRouter.tsx
  virtualFittingApp/src/pages/auth/ui/BrandSignUpPage.tsx
  virtualFittingApp/src/pages/brand/api/brand.action.ts
  virtualFittingApp/src/pages/brand/index.ts
  virtualFittingApp/src/pages/brand/types/brandUser.d.ts
  virtualFittingApp/src/pages/brand/ui/BrandAuthenticate.tsx
  virtualFittingApp/src/shared/config/axios/AxiosConfig.ts
  virtualFittingApp/src/widgets/auth/api/auth.action.ts
  virtualFittingApp/src/widgets/auth/api/brandAuth.action.ts
  virtualFittingApp/src/widgets/auth/hooks/useBrandSignup.tsx
  virtualFittingApp/src/widgets/auth/hooks/useLogin.tsx
  virtualFittingApp/src/widgets/auth/types/login.d.ts
  virtualFittingApp/src/widgets/auth/ui/BrandUserCompanySignUpPanel.tsx
  virtualFittingApp/src/widgets/auth/ui/BrandUserSignUp.tsx
Labels: feature, UI, Refactor

#172 [FE ⬅🚀 FE_mj] Refactor & Design : MyPage 디자인 부분 수정
  virtualFittingApp/bun.lock
  virtualFittingApp/package.json
  virtualFittingApp/public/svg/arrow.svg
  virtualFittingApp/public/svg/buttonDown.svg
  virtualFittingApp/public/svg/camera.svg
  virtualFittingApp/src/app/my/MyRouter.tsx
  virtualFittingApp/src/pages/my/constants/index.ts
  virtualFittingApp/src/pages/my/ui/MyCancel.tsx
  virtualFittingApp/src/pages/my/ui/MyLike.tsx
  virtualFittingApp/src/pages/my/ui/MyOrderList.tsx
  virtualFittingApp/src/pages/my/ui/MyOrderListDetail.tsx
  virtualFittingApp/src/pages/my/ui/MyPage.tsx
  virtualFittingApp/src/pages/my/ui/MyPageDetail.tsx
  virtualFittingApp/src/pages/my/ui/MyReview.tsx
  virtualFittingApp/src/pages/my/ui/arrow.png
  virtualFittingApp/src/shared/layout/index.ts
  virtualFittingApp/src/shared/layout/my/MyLayout.tsx
  virtualFittingApp/src/shared/styles/Theme.ts
Labels: UI, Refactor

#165 [FE ⬅🚀 FE_seah] UI 리팩토링 및 할인가격 API 연동
  virtualFittingApp/public/img/clothes/hoodie.png
  virtualFittingApp/public/svg/bag.svg
  virtualFittingApp/public/svg/menu.svg
  virtualFittingApp/public/svg/user.svg
  virtualFittingApp/src/App.css
  virtualFittingApp/src/app/payment/PaymentRouter.tsx
  virtualFittingApp/src/features/payment/index.ts
  virtualFittingApp/src/features/payment/ui/FailPage.tsx
  virtualFittingApp/src/pages/main/ui/MainPage.tsx
  virtualFittingApp/src/pages/my/ui/MyCancel.tsx
  virtualFittingApp/src/pages/my/ui/MyLike.tsx
  virtualFittingApp/src/pages/my/ui/MyOrderList.tsx
  virtualFittingApp/src/pages/my/ui/MyOrderListDetail.tsx
  virtualFittingApp/src/pages/my/ui/MyPage.tsx
  virtualFittingApp/src/pages/my/ui/MyPageDetail.tsx
  virtualFittingApp/src/pages/my/ui/MyReview.tsx
  virtualFittingApp/src/pages/my/ui/WriteReview.tsx
  virtualFittingApp/src/pages/store/api/payment.action.ts
  virtualFittingApp/src/pages/store/api/products.action.ts
  virtualFittingApp/src/pages/store/ui/StoreDetailPage.tsx
  virtualFittingApp/src/pages/store/ui/StorePage.tsx
  virtualFittingApp/src/shared/components/button/ui/AIButton.tsx
  virtualFittingApp/src/shared/components/button/ui/AddButton.tsx
  virtualFittingApp/src/shared/components/button/ui/PurchaseButton.tsx
  virtualFittingApp/src/shared/components/header/index.ts
  virtualFittingApp/src/shared/components/header/ui/Header.tsx
  virtualFittingApp/src/shared/components/header/ui/MyHeader.tsx
  virtualFittingApp/src/shared/components/index.ts
  virtualFittingApp/src/shared/components/payment/api/payment.action.ts
  virtualFittingApp/src/shared/components/payment/constants/index.ts
  virtualFittingApp/src/shared/components/payment/index.ts
  virtualFittingApp/src/shared/components/payment/types/imp.d.ts
  virtualFittingApp/src/shared/components/payment/types/paymentData.d.ts
  virtualFittingApp/src/shared/components/payment/types/paymentProps.d.ts
  virtualFittingApp/src/shared/components/payment/types/product.d.ts
  virtualFittingApp/src/shared/components/payment/types/userInfo.d.ts
  virtualFittingApp/src/shared/components/payment/ui/Payment.tsx
  virtualFittingApp/src/shared/components/payment/ui/PaymentButton.tsx
  virtualFittingApp/src/shared/components/product-card/ui/ProductCard.tsx
  virtualFittingApp/src/shared/constants/index.ts
  virtualFittingApp/src/shared/layout/index.ts
  virtualFittingApp/src/shared/layout/payment/PaymentLayout.tsx
  virtualFittingApp/src/shared/types/index.ts
  virtualFittingApp/src/shared/types/product/productPrice.d.ts
  virtualFittingApp/src/widgets/main/ui/AiServiceSection.tsx
  virtualFittingApp/src/widgets/store/ui/DetailDescription.tsx
  virtualFittingApp/src/widgets/store/ui/ProductContainer.tsx
  virtualFittingApp/src/widgets/store/ui/SizeInfo.tsx
Labels: feature, UI, Refactor

#177 [FE ⬅🚀 FE_seah] 쿠폰 조회 API, 가격 견적 조회 API 연동
  virtualFittingApp/.env.template
  virtualFittingApp/src/app/my/MyRouter.tsx
  virtualFittingApp/src/pages/main/ui/MainPage.tsx
  virtualFittingApp/src/pages/my/index.ts
  virtualFittingApp/src/pages/my/ui/MyPageDetail.tsx
  virtualFittingApp/src/pages/store/api/products.action.ts
  virtualFittingApp/src/shared/types/index.ts
  virtualFittingApp/src/shared/types/product/claimableCoupon.d.ts
  virtualFittingApp/src/shared/types/product/discountQuote.d.ts
  virtualFittingApp/src/widgets/store/ui/ProductContainer.tsx
Labels: feature
