Repository pjhcsols/VirtualFitting_System, pull requests merged in 2025-05, with the labels that each got.

#120 [FE ← 🚀 FE_SONU] Basilium Brand Landing Page 작업 &
  virtualFittingApp/public/rive/BasiliumPopLogo.riv
  virtualFittingApp/src/app/brand/BrandRouter.tsx
  virtualFittingApp/src/pages/brand/ui/BrandLogin.tsx
  virtualFittingApp/src/pages/brand/ui/BrandPage.tsx
  virtualFittingApp/src/pages/brand/ui/BrandProfile.tsx
  virtualFittingApp/src/pages/brand/ui/css/BrandLogin.css.ts
  virtualFittingApp/src/pages/brand/ui/css/BrandPage.css.ts
  virtualFittingApp/src/pages/my/ui/MyPage.tsx
  virtualFittingApp/src/shared/components/header/index.ts
  virtualFittingApp/src/shared/components/header/ui/BrandLandingHeader.tsx
  virtualFittingApp/src/shared/components/logo3D/index.ts
  virtualFittingApp/src/shared/components/logo3D/ui/BasiliumNoAnimationLogo .tsx
  virtualFittingApp/src/shared/components/logo3D/ui/PopLogo.tsx
  virtualFittingApp/src/widgets/brand/ui/BrandInfoChanger.tsx
Labels: feature, UI

#121 [FE ⬅🚀 FE_seah] Refactor Store Page
  virtualFittingApp/src/pages/store/api/product.action.ts
  virtualFittingApp/src/pages/store/constants/dummy.ts
  virtualFittingApp/src/shared/components/product-card/index.tsx
  virtualFittingApp/src/shared/components/product-card/ui/ColorPopUp.tsx
  virtualFittingApp/src/shared/components/product-card/ui/ProductCard.tsx
Labels: Refactor

#122 [FE ← FE_SONU] 🚀 Admin Brand User Management Page Design
  virtualFittingApp/public/svg/BasiliumLogo.svg
  virtualFittingApp/src/app/admin/AdminRouter.tsx
  virtualFittingApp/src/app/brand/BrandRouter.tsx
  virtualFittingApp/src/pages/admin/index.ts
  virtualFittingApp/src/pages/admin/ui/AdminBrandControllPanel.tsx
  virtualFittingApp/src/pages/admin/ui/AdminTotalUserList.tsx
  virtualFittingApp/src/pages/admin/ui/css/AdminBrandControllPanel.css.ts
  virtualFittingApp/src/pages/admin/ui/css/AdminTotalUserList.css.ts
  virtualFittingApp/src/shared/components/column/index.ts
  virtualFittingApp/src/shared/components/column/ui/AdminBrandUserColumn.tsx
  virtualFittingApp/src/shared/components/header/constants/index.ts
  virtualFittingApp/src/shared/components/header/index.ts
  virtualFittingApp/src/shared/components/header/ui/AdminHeader.tsx
  virtualFittingApp/src/shared/components/index.ts
  virtualFittingApp/src/shared/components/pagination/index.ts
  virtualFittingApp/src/shared/constants/index.ts
  virtualFittingApp/src/shared/layout/admin/AdminLayout.tsx
  virtualFittingApp/src/widgets/admin/api/admin.action.ts
  virtualFittingApp/src/widgets/admin/index.ts
  virtualFittingApp/src/widgets/admin/ui/AdminBrandUserList.tsx
  virtualFittingApp/src/widgets/admin/ui/BrandProductList.tsx
  virtualFittingApp/src/widgets/admin/ui/css/AdminBrandUserList.css.ts
  virtualFittingApp/src/widgets/brand/api/brand.action.ts
  virtualFittingApp/src/widgets/brand/index.ts
  virtualFittingApp/src/widgets/brand/ui/JudgeStandard.tsx
  virtualFittingApp/src/widgets/brand/ui/ProductEditor.tsx
  virtualFittingApp/src/widgets/brand/ui/ProductInputTag.tsx
  virtualFittingApp/src/widgets/brand/ui/ProductPreview.tsx
  virtualFittingApp/src/widgets/brand/ui/css/JudgeStandard.css.ts
  virtualFittingApp/src/widgets/brand/ui/css/ProductEditor.css.ts
  virtualFittingApp/src/widgets/brand/ui/css/ProductInputTag.css.ts
  virtualFittingApp/src/widgets/brand/ui/css/ProductPreview.css.ts
Labels: feature, UI

#125 [FE ⬅🚀 FE_seah] Refactor Store Page & Store Detail Page
  virtualFittingApp/public/svg/liked.svg
  virtualFittingApp/src/pages/store/ui/StoreDetailPage.tsx
  virtualFittingApp/src/shared/components/button/ui/LikeButton.tsx
  virtualFittingApp/src/shared/components/button/utils/items.util.ts
  virtualFittingApp/src/shared/components/product-card/ui/ProductCard.tsx
  virtualFittingApp/src/widgets/store/ui/ProductContainer.tsx
Labels: feature, UI, Refactor

#127 [FE ← FE_SONU] Brand User Login Page Design & Admin User Login Page working
  virtualFittingApp/public/rive/BasiliumSVGLogo.riv
  virtualFittingApp/src/app/admin/AdminRouter.tsx
  virtualFittingApp/src/app/login/LogInRouter.tsx
  virtualFittingApp/src/pages/admin/types/AdminUser.d.ts
  virtualFittingApp/src/pages/admin/ui/AdminLogin.tsx
  virtualFittingApp/src/pages/admin/ui/css/AdminLogin.css.ts
  virtualFittingApp/src/pages/admin/utils/text.utils.ts
  virtualFittingApp/src/pages/brand/index.ts
  virtualFittingApp/src/pages/brand/types/brandUser.d.ts
  virtualFittingApp/src/pages/brand/ui/BrandLogin.tsx
  virtualFittingApp/src/pages/brand/ui/css/BrandLogin.css.ts
  virtualFittingApp/src/shared/components/button/index.ts
  virtualFittingApp/src/shared/components/button/ui/LoginButton.tsx
  virtualFittingApp/src/shared/components/input/index.ts
  virtualFittingApp/src/shared/components/input/ui/LoginInput.tsx
  virtualFittingApp/src/shared/components/input/ui/css/LoginInput.css.ts
  virtualFittingApp/src/shared/components/logo3D/index.ts
  virtualFittingApp/src/shared/components/logo3D/ui/Basilium3DModelLogin.tsx
  virtualFittingApp/src/shared/components/logo3D/ui/BasiliumSVGLogo.tsx
Labels: feature, UI

#130 [FE ⬅🚀 FE_seah] Refactor Store Detail Page
  virtualFittingApp/public/svg/ai.svg
  virtualFittingApp/src/pages/store/ui/StoreDetailPage.tsx
  virtualFittingApp/src/shared/components/button/index.ts
  virtualFittingApp/src/shared/components/button/ui/AIButton.tsx
  virtualFittingApp/src/shared/components/button/utils/items.util.ts
  virtualFittingApp/src/shared/components/product/ui/ProductSmallCard.tsx
  virtualFittingApp/src/shared/constants/index.ts
  virtualFittingApp/src/shared/layout/store/StoreLayout.tsx
  virtualFittingApp/src/widgets/store/ui/ProductContainer.tsx
Labels: fix
