Repository pjhcsols/VirtualFitting_System, pull requests merged in 2025-03, with the labels that each got.

#92 [FE ⬅🚀 FE_mj] Refactor: SearchResult, myPage
  virtualFittingApp/bun.lock
  virtualFittingApp/package.json
  virtualFittingApp/src/pages/my/api/user.action.ts
  virtualFittingApp/src/pages/my/ui/MyPage.tsx
  virtualFittingApp/src/pages/my/ui/MyPageDetail.css
  virtualFittingApp/src/pages/my/ui/MyPageDetail.tsx
  virtualFittingApp/src/pages/search/SearchResult.css
  virtualFittingApp/src/pages/search/SearchResult.tsx
  virtualFittingApp/vite.config.ts
Labels: feature, fix, Refactor

#90 [FE ⬅🚀 FE_SONU] ✨ Hooks 를 이용해서, UI 와 React State 관리 및 onChange 와 같은 Logic 분리
  virtualFittingApp/src/app/index.ts
  virtualFittingApp/src/pages/admin/api/register.action.ts
  virtualFittingApp/src/pages/admin/hooks/useProduct.tsx
  virtualFittingApp/src/pages/admin/index.ts
  virtualFittingApp/src/pages/admin/types/Product.d.ts
  virtualFittingApp/src/pages/admin/ui/AdminCreateProductPage.tsx
  virtualFittingApp/src/pages/index.ts
  virtualFittingApp/src/pages/login/api/login.action.ts
  virtualFittingApp/src/pages/main/MainPage.tsx
  virtualFittingApp/src/pages/my/ui/MyPage.tsx
  virtualFittingApp/src/pages/store/api/store.action.ts
  virtualFittingApp/src/pages/store/hooks/useWholeProducts.tsx
  virtualFittingApp/src/pages/store/index.ts
  virtualFittingApp/src/shared/action/index.ts
  virtualFittingApp/src/shared/action/store/store.action.ts
  virtualFittingApp/src/shared/action/token/token.action.ts
  virtualFittingApp/src/shared/components/button/api/button.action.ts
  virtualFittingApp/src/shared/components/checkbox/CheckBox.tsx
  virtualFittingApp/src/shared/components/header/ui/Header.tsx
  virtualFittingApp/src/shared/components/product/hooks/useStoreProduct.tsx
  virtualFittingApp/src/shared/components/product/index.ts
  virtualFittingApp/src/shared/components/product/ui/StoreProduct.tsx
  virtualFittingApp/src/shared/components/searchBar/api/search.action.ts
  virtualFittingApp/src/shared/components/shopping-cart/ui/ShoppingCart.tsx
  virtualFittingApp/src/shared/config/axios/AxiosConfig.ts
  virtualFittingApp/src/shared/config/index.ts
  virtualFittingApp/src/shared/constants/index.ts
  virtualFittingApp/src/shared/hooks/index.ts
  virtualFittingApp/src/shared/hooks/scroll/useScrollDetector.tsx
  virtualFittingApp/src/shared/index.ts
  virtualFittingApp/src/shared/layout/admin/AdminLayout.tsx
  virtualFittingApp/src/shared/layout/admin/AdminSignLayout.tsx
  virtualFittingApp/src/shared/layout/index.ts
  virtualFittingApp/src/shared/layout/user/UserLayout.tsx
  virtualFittingApp/src/shared/layout/user/UserSignLayout.tsx
  virtualFittingApp/src/shared/types/auth/authContext.d.ts
  virtualFittingApp/src/shared/types/index.ts
  virtualFittingApp/src/shared/types/product/option.d.ts
  virtualFittingApp/src/shared/types/user/grade.d.ts
  virtualFittingApp/src/shared/types/user/user.d.ts
  virtualFittingApp/src/shared/utils/date/date.util.ts
  virtualFittingApp/src/shared/utils/index.ts
  virtualFittingApp/src/widgets/admin/index.ts
  virtualFittingApp/src/widgets/index.ts
  virtualFittingApp/src/widgets/store/index.ts
Labels: enhancement

#100 [FE ← 🚀 FE_seah] Update navbar & add carousel to Store Page
  virtualFittingApp/public/svg/bag.svg
  virtualFittingApp/public/svg/cart.svg
  virtualFittingApp/public/svg/cart_white.svg
  virtualFittingApp/public/svg/menu.svg
  virtualFittingApp/public/svg/store_test.svg
  virtualFittingApp/public/svg/store_test2.svg
  virtualFittingApp/public/svg/store_test3.svg
  virtualFittingApp/public/svg/user.svg
  virtualFittingApp/public/svg/user_white.svg
  virtualFittingApp/src/app/store/StoreRouter.tsx
  virtualFittingApp/src/pages/store/ui/StorePage.tsx
  virtualFittingApp/src/shared/components/header/constants/index.ts
  virtualFittingApp/src/shared/components/header/ui/Header.tsx
  virtualFittingApp/src/shared/components/header/ui/NewHeader.tsx
  virtualFittingApp/src/shared/layout/index.ts
  virtualFittingApp/src/shared/layout/store/StoreLayout.tsx
  virtualFittingApp/src/widgets/store/constants/index.ts
  virtualFittingApp/src/widgets/store/index.ts
  virtualFittingApp/src/widgets/store/ui/Banner.tsx
  virtualFittingApp/src/widgets/store/ui/Carousel.tsx
Labels: enhancement, feature

#101 [FE ⬅🚀 FE_mj] Fix & Refactor MyPage & MypageDetail
  virtualFittingApp/src/App.tsx
  virtualFittingApp/src/app/my/MyRouter.tsx
  virtualFittingApp/src/pages/my/ui/MyPage.tsx
  virtualFittingApp/src/pages/my/ui/MyPageDetail.css
  virtualFittingApp/src/pages/my/ui/MyPageDetail.tsx
  virtualFittingApp/src/shared/components/header/index.ts
  virtualFittingApp/src/shared/components/header/ui/MyHeader.tsx
  virtualFittingApp/src/shared/components/header/ui/UserImg.png
  virtualFittingApp/src/shared/components/header/ui/back.png
  virtualFittingApp/tsconfig.app.json
Labels: feature, fix, Refactor
